### ISSUE TITLE
Hide seconds on tap

### ISSUE THREAD

**Issue by fvdm** [mikaoj/Binary-Clock#1]
Hi, I like your binary clock app on the Apple TV. Only the seconds are bit too much activity for me, especially in the evening.

Would it be possible to add an option to hide the seconds when you tap on the remote?

That way the app can keep its simplicity.

**Comment by mikaoj** [comment]
Yeah sure why not...is it something you would be interested in doing or was it more of a feature request? 😄

**Comment by fvdm** [comment]
It's a request 😉 my Swift skills are non-existing.
